#!/usr/bin/env bash

# Dependencies
# gem install scss_lint

# Packages
apm install editorconfig
apm install linter
apm install linter-php
apm install linter-jsonlint
apm install linter-jshint
apm install linter-csslint
apm install linter-scss-lint
apm install atom-wordpress
apm install autocomplete-wordpress-hooks

# Themes
apm install seti-ui
