#!/usr/bin/env bash

# gem install scss_lint

apm install editorconfig
apm install linter
apm install linter-php
apm install linter-jsonlint
apm install linter-jshint
apm install linter-csslint
apm install linter-scss-lint
apm install atom-wordpress
apm install autocomplete-wordpress-hooks
